name: iot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.3
  firebase_database: ^10.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/termo.png
    - assets/balan.png
    - assets/InventarOI.png
    - assets/past.png
    - assets/snack.png
